apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: xnrk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xnrk
    app.kubernetes.io/part-of: byoc-app-joym
  name: xnrk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: xnrk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: xnrk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-dieq-tenant/byoc-app-joym/xnrk@sha256:17317c5d5f4a3fbecf3e0847a814666ec97c30b7b55c83bc3beb2e3c9e42e070
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
